namespace NewsSite.Server.Models.ChatSettings
{
    public class OpenAiChatResponse
    {
        // Represents a single choice returned by the API
        public class ChatChoice
        {
            public string Role { get; set; } // The role of the message (e.g., "assistant")
            public string Content { get; set; } // The actual content of the message
        }

        // All messages generated by OpenAI in this response
        public List<ChatChoice> Choices { get; set; } = new List<ChatChoice>();

        // Token usage information
        public int TotalTokensUsed { get; set; }
        public int PromptTokens { get; set; }
        public int CompletionTokens => TotalTokensUsed - PromptTokens;

        // Convenience method to get the first choice content
        public string FirstChoiceContent => Choices.Count > 0 ? Choices[0].Content : string.Empty;
    }
}
